version: '3.2'
services:
  postgres:
    image: 'postgres:latest'
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
  node_backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - 5001:5000
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_EXT_PORT=5432
      - POSTGRES_HOST
  js_frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./Food
    ports:
      - 8081:80
    volumes:
      - ./Food:/usr/share/nginx/html
    
